### ISSUE TITLE
[Help Wanted] Compiled build possible?

### ISSUE THREAD

**Issue by cyber-speed** [ryobg/obj2hmap#2]
Hello,

Just came across this repo and been looking for  awhile for a way to convert OBJ terrain to a height map in RAW format.

Is there a way to gain access to a compiled build for windows for those of us who don't have the required files or knowledge to do so?
I would love to give it a try to see if it will work for some of my old projects, but i currently cant find a possible way to do so.

Cheers.

**Comment by ryobg** [comment]
Did one here https://github.com/ryobg/obj2hmap/releases/tag/1.0.0
